"""change_author_to_text

Revision ID: f8aa067a3718
Revises: 001
Create Date: 2026-03-16 23:22:58.902747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8aa067a3718'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_contents_article_id_key', 'article_contents', type_='unique')
    op.drop_index('ix_article_contents_article_id', table_name='article_contents')
    op.create_index(op.f('ix_article_contents_article_id'), 'article_contents', ['article_id'], unique=True)
    op.drop_constraint('article_fingerprints_article_id_key', 'article_fingerprints', type_='unique')
    op.create_index(op.f('ix_article_fingerprints_article_id'), 'article_fingerprints', ['article_id'], unique=True)
    op.create_index(op.f('ix_article_fingerprints_content_simhash'), 'article_fingerprints', ['content_simhash'], unique=False)
    op.drop_constraint('article_scores_article_id_key', 'article_scores', type_='unique')
    op.create_index(op.f('ix_article_scores_article_id'), 'article_scores', ['article_id'], unique=True)
    op.alter_column('articles', 'author',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_email_deliveries_version_id'), 'email_deliveries', ['version_id'], unique=False)
    op.create_index(op.f('ix_job_execution_logs_job_type'), 'job_execution_logs', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_execution_logs_status'), 'job_execution_logs', ['status'], unique=False)
    op.drop_constraint('uq_recipients_email', 'recipients', type_='unique')
    op.drop_index('ix_recipients_email', table_name='recipients')
    op.create_index(op.f('ix_recipients_email'), 'recipients', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipients_email'), table_name='recipients')
    op.create_index('ix_recipients_email', 'recipients', ['email'], unique=False)
    op.create_unique_constraint('uq_recipients_email', 'recipients', ['email'])
    op.drop_index(op.f('ix_job_execution_logs_status'), table_name='job_execution_logs')
    op.drop_index(op.f('ix_job_execution_logs_job_type'), table_name='job_execution_logs')
    op.drop_index(op.f('ix_email_deliveries_version_id'), table_name='email_deliveries')
    op.alter_column('articles', 'author',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_index(op.f('ix_article_scores_article_id'), table_name='article_scores')
    op.create_unique_constraint('article_scores_article_id_key', 'article_scores', ['article_id'])
    op.drop_index(op.f('ix_article_fingerprints_content_simhash'), table_name='article_fingerprints')
    op.drop_index(op.f('ix_article_fingerprints_article_id'), table_name='article_fingerprints')
    op.create_unique_constraint('article_fingerprints_article_id_key', 'article_fingerprints', ['article_id'])
    op.drop_index(op.f('ix_article_contents_article_id'), table_name='article_contents')
    op.create_index('ix_article_contents_article_id', 'article_contents', ['article_id'], unique=False)
    op.create_unique_constraint('article_contents_article_id_key', 'article_contents', ['article_id'])
    # ### end Alembic commands ###
